# Generated by Django 3.2.25 on 2025-07-31 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmerproduct',
            name='avaiable',
        ),
        migrations.RemoveField(
            model_name='farmerproduct',
            name='price',
        ),
        migrations.RemoveField(
            model_name='farmerproduct',
            name='unit',
        ),
        migrations.AddField(
            model_name='farmerproduct',
            name='amount',
            field=models.CharField(default='NONE', max_length=20),
        ),
        migrations.AddField(
            model_name='farmerproduct',
            name='available_quantity',
            field=models.CharField(default='NONE', max_length=20),
        ),
        migrations.AddField(
            model_name='farmerproduct',
            name='description',
            field=models.CharField(default='NONE', max_length=220),
        ),
        migrations.AddField(
            model_name='farmerproduct',
            name='image_1',
            field=models.ImageField(default='farmer.jpg', upload_to='image/'),
        ),
        migrations.AddField(
            model_name='farmerproduct',
            name='image_2',
            field=models.ImageField(default='farmer.jpg', upload_to='image/'),
        ),
        migrations.AddField(
            model_name='farmerproduct',
            name='image_3',
            field=models.ImageField(default='farmer.jpg', upload_to='image/'),
        ),
        migrations.AddField(
            model_name='farmerproduct',
            name='image_4',
            field=models.ImageField(default='farmer.jpg', upload_to='image/'),
        ),
        migrations.AddField(
            model_name='farmerproduct',
            name='per_unit',
            field=models.CharField(default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='farmerproduct',
            name='category',
            field=models.CharField(default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='farmerproduct',
            name='product_name',
            field=models.CharField(default='NONE', max_length=20),
        ),
    ]
