# Generated by Django 3.2.25 on 2025-07-31 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0002_auto_20250731_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerproduct',
            name='amount',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='farmerproduct',
            name='available_quantity',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='farmerproduct',
            name='category',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='farmerproduct',
            name='description',
            field=models.CharField(default='', max_length=220),
        ),
        migrations.AlterField(
            model_name='farmerproduct',
            name='per_unit',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='farmerproduct',
            name='product_name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
