# Generated by Django 3.2.25 on 2025-08-01 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0003_auto_20250731_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerproduct',
            name='username',
            field=models.CharField(default='', max_length=20),
        ),
    ]
