# Generated by Django 3.2.25 on 2025-08-01 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0004_farmerproduct_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerproduct',
            name='no_of_uploads',
            field=models.IntegerField(default=0),
        ),
    ]
