# Generated by Django 3.2.25 on 2025-08-01 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0005_farmerproduct_no_of_uploads'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerproduct',
            name='password',
            field=models.CharField(default='', max_length=20),
        ),
    ]
