# Generated by Django 3.2.25 on 2025-08-01 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0006_farmerproduct_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmerproduct',
            name='no_of_uploads',
        ),
    ]
