# Generated by Django 3.2.25 on 2025-08-05 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0007_remove_farmerproduct_no_of_uploads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerproduct',
            name='image_1',
            field=models.ImageField(default='farmer.jpg', upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='farmerproduct',
            name='image_2',
            field=models.ImageField(default='farmer.jpg', upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='farmerproduct',
            name='image_3',
            field=models.ImageField(default='farmer.jpg', upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='farmerproduct',
            name='image_4',
            field=models.ImageField(default='farmer.jpg', upload_to='media/'),
        ),
    ]
