# Generated by Django 3.2.25 on 2025-08-05 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0008_auto_20250805_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerproduct',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='farmerproduct',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='farmerproduct',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='farmerproduct',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
