# Generated by Django 3.2.25 on 2025-08-05 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0009_auto_20250805_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerproduct',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='media/products/'),
        ),
    ]
