# Generated by Django 3.2.25 on 2025-08-05 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0010_alter_farmerproduct_image_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerproduct',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
