# Generated by Django 3.2.25 on 2025-08-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0011_alter_farmerproduct_image_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerproduct',
            name='address',
            field=models.CharField(default='', max_length=20),
        ),
    ]
