# Generated by Django 3.2.25 on 2025-08-08 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0012_farmerproduct_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerproduct',
            name='address',
            field=models.CharField(default='', max_length=1200),
        ),
    ]
