# Generated by Django 3.2.25 on 2025-08-09 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0013_alter_farmerproduct_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmerproduct',
            old_name='username',
            new_name='farmer_name',
        ),
    ]
