# Generated by Django 3.2.25 on 2025-08-12 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0015_acceptcart'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptcart',
            name='add_caartid',
            field=models.CharField(default='', max_length=20),
        ),
    ]
