# Generated by Django 3.2.25 on 2025-08-12 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0016_acceptcart_add_caartid'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptcart',
            name='total',
            field=models.CharField(default='', max_length=20),
        ),
    ]
