# Generated by Django 3.2.25 on 2025-08-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0017_acceptcart_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='farmmprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=20)),
                ('password', models.CharField(default='', max_length=20)),
                ('email', models.CharField(default='', max_length=20)),
                ('phone', models.CharField(default='', max_length=20)),
                ('farmname', models.CharField(default='', max_length=20)),
                ('location', models.CharField(default='', max_length=220)),
                ('date', models.CharField(default='', max_length=220)),
            ],
        ),
    ]
