# Generated by Django 3.2.25 on 2025-08-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0018_farmmprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmmprofile',
            name='img_1',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
