# Generated by Django 3.2.25 on 2025-08-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='addcart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=20)),
                ('product_name', models.CharField(default='', max_length=20)),
                ('image_1', models.ImageField(upload_to='cart/')),
                ('quantity', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
