# Generated by Django 3.2.25 on 2025-08-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcart',
            name='amount',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='addcart',
            name='destination',
            field=models.CharField(default='', max_length=220),
        ),
    ]
