# Generated by Django 3.2.25 on 2025-08-08 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporter', '0002_auto_20250806_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcart',
            name='fromm',
            field=models.CharField(default='', max_length=1200),
        ),
    ]
