# Generated by Django 3.2.25 on 2025-08-09 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporter', '0003_addcart_fromm'),
    ]

    operations = [
        migrations.CreateModel(
            name='acceptcart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.CharField(default='', max_length=50)),
                ('status', models.CharField(default='New', max_length=20)),
                ('product_name', models.CharField(default='', max_length=20)),
                ('quantity', models.CharField(default='', max_length=20)),
                ('price_per_kg', models.CharField(default=0, max_length=20)),
                ('note', models.CharField(default='Note', max_length=1200)),
                ('customer_name', models.CharField(default='', max_length=20)),
                ('phone', models.CharField(default=0, max_length=10)),
                ('image_1', models.ImageField(upload_to='cart/')),
                ('fromm', models.CharField(default='', max_length=1200)),
                ('to', models.CharField(default='', max_length=220)),
            ],
        ),
        migrations.DeleteModel(
            name='addcart',
        ),
    ]
