# Generated by Django 3.2.25 on 2025-08-11 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporter', '0004_auto_20250809_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='acceptedorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='', max_length=20)),
                ('transporter_name', models.CharField(default='', max_length=20)),
                ('customer_name', models.CharField(default='', max_length=20)),
                ('quantity', models.CharField(default='', max_length=20)),
                ('price_per_kg', models.CharField(default=0, max_length=20)),
                ('phone', models.CharField(default=0, max_length=10)),
                ('image_1', models.ImageField(upload_to='cart/')),
                ('fromm', models.CharField(default='', max_length=1200)),
                ('to', models.CharField(default='', max_length=220)),
            ],
        ),
    ]
