# Generated by Django 3.2.25 on 2025-08-11 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transporter', '0005_acceptedorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='acceptcart',
        ),
    ]
