# Generated by Django 3.2.25 on 2025-08-12 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporter', '0006_delete_acceptcart'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptedorder',
            name='status',
            field=models.CharField(default='', max_length=20),
        ),
    ]
