# Generated by Django 3.2.25 on 2025-08-12 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporter', '0007_acceptedorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptedorder',
            name='created_at',
            field=models.CharField(default='', max_length=50),
        ),
    ]
