# Generated by Django 3.2.25 on 2025-08-12 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporter', '0008_acceptedorder_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptedorder',
            name='accept_cart_id',
            field=models.CharField(default='', max_length=220),
        ),
        migrations.AddField(
            model_name='acceptedorder',
            name='accept_order_id',
            field=models.CharField(default='', max_length=220),
        ),
    ]
