# Generated by Django 3.2.25 on 2025-07-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cracc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=25)),
                ('occupation', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=40)),
                ('phone_no', models.IntegerField(max_length=10)),
            ],
        ),
    ]
