# Generated by Django 3.2.25 on 2025-07-28 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cracc',
            name='phone_no',
            field=models.IntegerField(),
        ),
    ]
