# Generated by Django 3.2.25 on 2025-08-01 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_cracc_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='cracc',
            name='no_of_uploads',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cracc',
            name='phone_no',
            field=models.IntegerField(default=0),
        ),
    ]
