# Generated by Django 3.2.25 on 2025-08-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20250801_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='cracc',
            name='date',
            field=models.CharField(default='', max_length=40),
        ),
    ]
