# Generated by Django 3.2.25 on 2025-08-09 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcart',
            name='total',
            field=models.CharField(default='', max_length=20),
        ),
    ]
