# Generated by Django 3.2.25 on 2025-08-09 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_addcart_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcart',
            name='farmer_name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
