# Generated by Django 3.2.25 on 2025-08-13 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_addcart_farmer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcart',
            name='acceptcartid',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='addcart',
            name='acceptedcartid',
            field=models.CharField(default='', max_length=20),
        ),
    ]
